/// Znaczniki identyfikatorów są celowo puste.
/// Ich jedyną funkcją jest uniemożliwienie mieszania ID różnych encji.
public enum ProjectIDTag: Sendable {}
public enum CustomerIDTag: Sendable {}
public enum ProjectSiteIDTag: Sendable {}
public enum RoomIDTag: Sendable {}
public enum WallIDTag: Sendable {}
public enum ContourSegmentIDTag: Sendable {}
public enum OpeningIDTag: Sendable {}
public enum WindowIDTag: Sendable {}
public enum DoorIDTag: Sendable {}
public enum RecessIDTag: Sendable {}
public enum ObstacleIDTag: Sendable {}
public enum InstallationPointIDTag: Sendable {}
public enum WallProfileIDTag: Sendable {}
public enum WallProfilePointIDTag: Sendable {}
public enum BayProjectionIDTag: Sendable {}
public enum MeasurementIDTag: Sendable {}
public enum RevisionIDTag: Sendable {}
public enum FurnitureAssemblyIDTag: Sendable {}
public enum FurniturePlacementIDTag: Sendable {}
public enum FurnitureRunIDTag: Sendable {}
public enum FurnitureTemplateIDTag: Sendable {}
public enum SubassemblyIDTag: Sendable {}
public enum ComponentIDTag: Sendable {}
public enum PanelIDTag: Sendable {}
public enum CabinetIDTag: Sendable {}
public enum ConstraintIDTag: Sendable {}
public enum HardwareProfileIDTag: Sendable {}
public enum SupplierIDTag: Sendable {}
public enum SupplierProductIDTag: Sendable {}
public enum PriceListIDTag: Sendable {}
public enum ImportBatchIDTag: Sendable {}
public enum TechnicalDocumentIDTag: Sendable {}
public enum DrawingSheetIDTag: Sendable {}

public typealias ProjectID = EntityID<ProjectIDTag>
public typealias CustomerID = EntityID<CustomerIDTag>
public typealias ProjectSiteID = EntityID<ProjectSiteIDTag>
public typealias RoomID = EntityID<RoomIDTag>
public typealias WallID = EntityID<WallIDTag>
public typealias ContourSegmentID = EntityID<ContourSegmentIDTag>
public typealias OpeningID = EntityID<OpeningIDTag>
public typealias WindowID = EntityID<WindowIDTag>
public typealias DoorID = EntityID<DoorIDTag>
public typealias RecessID = EntityID<RecessIDTag>
public typealias ObstacleID = EntityID<ObstacleIDTag>
public typealias InstallationPointID = EntityID<InstallationPointIDTag>
public typealias WallProfileID = EntityID<WallProfileIDTag>
public typealias WallProfilePointID = EntityID<WallProfilePointIDTag>
public typealias BayProjectionID = EntityID<BayProjectionIDTag>
public typealias MeasurementID = EntityID<MeasurementIDTag>
public typealias RevisionID = EntityID<RevisionIDTag>
public typealias FurnitureAssemblyID = EntityID<FurnitureAssemblyIDTag>
public typealias FurniturePlacementID = EntityID<FurniturePlacementIDTag>
public typealias FurnitureRunID = EntityID<FurnitureRunIDTag>
public typealias FurnitureTemplateID = EntityID<FurnitureTemplateIDTag>
public typealias SubassemblyID = EntityID<SubassemblyIDTag>
public typealias ComponentID = EntityID<ComponentIDTag>
public typealias PanelID = EntityID<PanelIDTag>
public typealias CabinetID = EntityID<CabinetIDTag>
public typealias ConstraintID = EntityID<ConstraintIDTag>
public typealias HardwareProfileID = EntityID<HardwareProfileIDTag>
public typealias SupplierID = EntityID<SupplierIDTag>
public typealias SupplierProductID = EntityID<SupplierProductIDTag>
public typealias PriceListID = EntityID<PriceListIDTag>
public typealias ImportBatchID = EntityID<ImportBatchIDTag>
public typealias TechnicalDocumentID = EntityID<TechnicalDocumentIDTag>
public typealias DrawingSheetID = EntityID<DrawingSheetIDTag>
